More debug logging

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -150,13 +150,17 @@ jobs:
             --overlay-triplets="${GITHUB_WORKSPACE}/vcpkg-triplets" \
             --debug; then
             echo '=== Build failed, dumping logs ==='
-            echo '=== config-${{ matrix.platform.triplet }}-out.log ==='
+            echo '=== buildtrees/detect_compiler/config-${{ matrix.platform.triplet }}-out.log ==='
+            cat ${GITHUB_WORKSPACE}/vcpkg/buildtrees/detect_compiler/config-${{ matrix.platform.triplet }}-out.log 2>/dev/null || echo 'Log file not found'
+            echo '=== buildtrees/detect_compiler/config-${{ matrix.platform.triplet }}-rel-CMakeCache.txt.log ==='
+            cat ${GITHUB_WORKSPACE}/vcpkg/buildtrees/detect_compiler/config-${{ matrix.platform.triplet }}-rel-CMakeCache.txt.log 2>/dev/null || echo 'Log file not found'
+            echo '=== buildtrees/rocksdb/config-${{ matrix.platform.triplet }}-out.log ==='
             cat ${GITHUB_WORKSPACE}/vcpkg/buildtrees/rocksdb/config-${{ matrix.platform.triplet }}-out.log 2>/dev/null || echo 'Log file not found'
-            echo '=== config-${{ matrix.platform.triplet }}-err.log ==='
+            echo '=== buildtrees/rocksdb/config-${{ matrix.platform.triplet }}-err.log ==='
             cat ${GITHUB_WORKSPACE}/vcpkg/buildtrees/rocksdb/config-${{ matrix.platform.triplet }}-err.log 2>/dev/null || echo 'Log file not found'
-            echo '=== install-${{ matrix.platform.triplet }}-dbg-out.log ==='
+            echo '=== buildtrees/rocksdb/install-${{ matrix.platform.triplet }}-dbg-out.log ==='
             cat ${GITHUB_WORKSPACE}/vcpkg/buildtrees/rocksdb/install-${{ matrix.platform.triplet }}-dbg-out.log 2>/dev/null || echo 'Log file not found'
-            echo '=== install-${{ matrix.platform.triplet }}-dbg-err.log ==='
+            echo '=== buildtrees/rocksdb/install-${{ matrix.platform.triplet }}-dbg-err.log ==='
             cat ${GITHUB_WORKSPACE}/vcpkg/buildtrees/rocksdb/install-${{ matrix.platform.triplet }}-dbg-err.log 2>/dev/null || echo 'Log file not found'
             exit 1
           fi
