Try to dump the downloads

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -188,18 +188,16 @@ jobs:
                 git \
                 linux-headers \
                 musl-dev \
-                ninja \
                 pkgconf \
                 tar \
                 zip
 
-              echo "================================================"
+              echo "=== CMake ==="
               cmake --version
-              ninja --version
 
+              echo "=== ROCKSDB_DIR ==="
               export ROCKSDB_DIR='/workspace/rocksdb-${{ needs.check.outputs.version }}'
-              echo \"ROCKSDB_DIR=\$ROCKSDB_DIR\"
-              echo "================================================"
+              echo \"\$ROCKSDB_DIR\"
 
               VCPKG_FORCE_SYSTEM_BINARIES=1 /workspace/vcpkg/bootstrap-vcpkg.sh -musl
 
@@ -216,7 +214,12 @@ jobs:
               fi
 
               cp -r /workspace/vcpkg/installed/${{ matrix.platform.triplet }}/* /workspace/dist/
-            "
+            " || true
+          echo "Build failed, dumping logs..."
+          find /workspace/vcpkg/downloads
+          cat /workspace/vcpkg/buildtrees/rocksdb/install-${{ matrix.platform.triplet }}-dbg-out.log 2>/dev/null || echo 'Log file not found'
+          cat /workspace/vcpkg/buildtrees/rocksdb/install-${{ matrix.platform.triplet }}-dbg-err.log 2>/dev/null || echo 'Log file not found'
+          exit 1
 
       - name: Create archive
         id: archive
